theme = "kanagawa"
# ferra is nice
#flatwhite is nice too
#hex_lavender is good
#monokai_pro_ristretto
#solarized_light
#
[editor]
line-number = "absolute"
mouse = false
true-color = true
color-modes = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
[keys.normal]
Z = {Q = ":q!", Z = ":wq" }
V = ["select_mode", "extend_to_line_bounds"]
x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
